create table users
(
    username    varchar(30) not null unique,
    password varchar(80) not null,
    primary key (username)
);

CREATE TABLE users_files
(
    id        bigint generated by default as identity,
    file_name varchar(255) not null,
    file_size bigint,
    user_username varchar(100),
    file_path varchar not null,
    primary key (id)
);

create table users_user_files
(
    user_username       varchar(255) not null,
    user_files_file_name varchar(255) not null
);

insert into users (username, password)
values ('test1@test.ru', '$2a$10$N3wQfECfA2jO768yuc1ElO2Y3WhcGFQzILU8N2pTGGD.JNjfrNNDu'), -- пароль password
       ('test2@test.ru', '$2a$10$Qb41t98c7mhLFmQqJGvPy.InEF1XNcPYZSG/vU0iIF9VWliPci4Ly'); -- пароль password